[workspace]
authors = ["Junjie Zhang <junj.jay.zhang@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "boring-shits"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
numpy = ">=2.4.1,<3"
